### ISSUE TITLE
# Error: line 1: level must be >= 0

### ISSUE THREAD

**Issue by codyrchildress** [bohdon/maya-workflowtools#1]
I am hoping to give these tools a test drive but upon first downloading this and pymetanode then running the .registerHotkeys() setup I get the following error:

```
# Error: line 1: level must be >= 0
# # Traceback (most recent call last):
# #   File "<maya console>", line 8, in <module>
# #   File "<maya console>", line 6, in <module>
# #   File "C:\Users\codyr\OneDrive\Documents\maya\modules\workflowtools\scripts\quickmenus\core.py", line 203, in buildMenus
# #     inst = menuCls()
# #   File "C:\Users\codyr\OneDrive\Documents\maya\modules\workflowtools\scripts\quickmenus\fmenus\menus.py", line 296, in __init__
# #     super(self.__class__, self).__init__()
# #   File "C:\Users\codyr\OneDrive\Documents\maya\modules\workflowtools\scripts\quickmenus\core.py", line 320, in __init__
# #     self.panel = pm.getPanel(underPointer=True)
# #   File "C:\Users\codyr\AppData\Roaming\Python\Python39\site-packages\pymel\core\windows.py", line 3121, in getPanel
# #     res = func(res)
# #   File "C:\Users\codyr\AppData\Roaming\Python\Python39\site-packages\pymel\internal\factories.py", line 318, in toGivenClass
# #     module = __import__(moduleName, globals(), locals(), [objectName], -1)
# # ValueError: level must be >= 0
```

I'm using Maya 2023. Is there some additional setup process I am missing?

**Comment by bohdon** [comment]
Hey, yeah unfortunately that's a bug in pymel, they haven't fully updated everything for Python 3 yet it seems. I submitted a PR a while back but there hasn't been a lot of activity on their github: https://github.com/LumaPictures/pymel/pull/445.

So far I've just been patching the pymel installation with the fix in that pull request. It's only two lines so generally easy to do. But I should consider working around it since its been over a year and they still haven't fixed it. 😞

**Comment by codyrchildress** [comment]
Thank you for the info. I was able to easily patch the pymel files and everything is now working wonderfully. This is a fantastic set of tools here!
